local helper = require("windows.helper")

-- Move between windows
vim.keymap.set({ "n", "i", "t" }, "<M-h>", "<cmd>wincmd h<Enter>")
vim.keymap.set({ "n", "i", "t" }, "<M-j>", "<cmd>wincmd j<Enter>")
vim.keymap.set({ "n", "i", "t" }, "<M-k>", "<cmd>wincmd k<Enter>")
vim.keymap.set({ "n", "i", "t" }, "<M-l>", "<cmd>wincmd l<Enter>")

-- Resizing windows
vim.keymap.set({ "n", "t" }, "<M-S-h>", function()
    helper.resize_window("left")
end)
vim.keymap.set({ "n", "t" }, "<M-S-j>", function()
    helper.resize_window("down")
end)
vim.keymap.set({ "n", "t" }, "<M-S-k>", function()
    helper.resize_window("up")
end)
vim.keymap.set({ "n", "t" }, "<M-S-l>", function()
    helper.resize_window("right")
end)

-- Moving windows
vim.keymap.set({ "n", "t" }, "<M-S-Left>", function()
    helper.swap_window_buffers("left")
end)
vim.keymap.set({ "n", "t" }, "<M-S-Down>", function()
    helper.swap_window_buffers("down")
end)
vim.keymap.set({ "n", "t" }, "<M-S-Up>", function()
    helper.swap_window_buffers("up")
end)
vim.keymap.set({ "n", "t" }, "<M-S-Right>", function()
    helper.swap_window_buffers("right")
end)
